spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cis_info
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: Property-Services
    
server:
  port: 8082
  
eureka:
  instance:
    hostname: localhost