spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crudusers
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

  application:
    name: Customer-Services
    
server:
  port: 8081
  
eureka:
  instance:
    hostname: localhost


    